Update cbox_chpasswdop

diff --git a/bin/cbox_chpasswdop b/bin/cbox_chpasswdop
--- a/bin/cbox_chpasswdop
+++ b/bin/cbox_chpasswdop
@@ -1,8 +1,7 @@
 #!/bin/bash
 #
-# Configured script to set Ethernet and WiFi configuration
+# Configured script to change user password by him/sheself
 #
-
 source /usr/local/bin/passwdmgmt
 source /usr/local/bin/configmgmt
 source /usr/local/bin/writelog
@@ -19,88 +18,46 @@ function acct_check() {
 }
 
 while true; do
-	prompt="Select function options: "
-	options=("List local accounts"
-		"Change local account password")
+	echo "Change local account password: "
 	echo ""
+	declare ACCT_NAME="$PORTEX_USERID"
+
+	read -sp "Enter old password: " PWD_OLD
 	echo ""
-	PS3="$prompt "
-	select opt in "${options[@]}" "Quit"; do
-		case "$REPLY" in
-		1)
-			echo "List local accounts: "
-			echo ""
-			echo "Local accounts on this host: "
-			for ITEM in $(cat $PORTEX_TS_CONF | egrep -v '#' | egrep ':localuser:'); do
-				ACCOUNT=$(echo $ITEM | awk -F: '{print $1}')
-				PRIVILEGE=$(echo $ITEM | awk -F: '{print $3}')
-				echo "Account:$ACCOUNT	Privilege:$PRIVILEGE"
-			done
-			echo ""
-			;;
-		2)
-			echo "Change local account password: "
-			echo ""
-			declare ACCT_NAME=""
-			while [ ! $ACCT_NAME ]; do
-				read -p "Enter account to change password: " ACCT_NAME
-			done
-			ACCOUNT=$(acct_check $ACCT_NAME)
-			case $ACCOUNT in
-			2)
-				echo "User account is not existed; try again."
-				break
-				;;
-			*) ;;
-			esac
-			read -sp "Enter old password: " PWD_OLD
-			echo ""
-			LOCAL_ACCT_NAME=$(cat $PORTEX_TS_CONF | egrep -v '#' | egrep "^$ACCT_NAME:localuser:" | awk -F: '{print $1}')
-			LOCAL_ACCT_PRIVILEGE=$(cat $PORTEX_TS_CONF | egrep -v '#' | egrep "^$ACCT_NAME:localuser:" | awk -F: '{print $3}')
-			LOCAL_ACCT_CRYPT=$(cat $PORTEX_TS_CONF | egrep -v '#' | egrep "^$ACCT_NAME:localuser:" | awk -F: '{print $4}')
-			echo $LOCAL_ACCT_NAME $LOCAL_ACCT_PRIVILEGE $LOCAL_ACCT_CRYPT
-			PASS_CHECK -c $PWD_OLD:$LOCAL_ACCT_CRYPT
-			if [ $? -eq 1 ]; then
-				echo "Old password is not correct; try again."
-				break
-			fi
-			read -sp "Enter new password: " PWD_INPUT
-			echo ""
-			read -sp "Retype new password: " PWD_INPUT2
-			echo ""
-			NEWPASS_CHECK $PWD_INPUT $PWD_INPUT2
-			case $? in
-			0)
-				echo "God job!"
-				ACCT_PRIV=$(cat $PORTEX_TS_CONF | egrep "^$ACCT_NAME" | awk -F: '{print $3}')
-				PWD_SALT=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)
-				OUTPUT_CRYPT=$(mkpasswd --method=SHA-512 -S $PWD_SALT $PWD_INPUT)
-				echo $LOCAL_ACCT_NAME:localuser:$LOCAL_ACCT_PRIVILEGE:$OUTPUT_CRYPT
-				CONFIG_CHANGE -d $ACCT_NAME:localuser:
-				CONFIG_CHANGE -a $ACCT_NAME:localuser:$ACCT_PRIV:$OUTPUT_CRYPT
-				;;
-			1)
-				NEWPASS_NOTIFY
-				break
-				;;
-			2)
-				echo "User password does not match, try again."
-				;;
-			*)
-				echo "Fetal error."
-				break
-				;;
-			esac
-			echo ""
-			;;
-		$((${#options[@]} + 1)))
-			echo "Goodbye!"
-			exit
-			;;
-		*)
-			echo "Invalid option. Try another one."
-			continue
-			;;
-		esac
-	done
+	LOCAL_ACCT_NAME=$(cat $PORTEX_TS_CONF | egrep -v '#' | egrep "^$ACCT_NAME:localuser:" | awk -F: '{print $1}')
+	LOCAL_ACCT_PRIVILEGE=$(cat $PORTEX_TS_CONF | egrep -v '#' | egrep "^$ACCT_NAME:localuser:" | awk -F: '{print $3}')
+	LOCAL_ACCT_CRYPT=$(cat $PORTEX_TS_CONF | egrep -v '#' | egrep "^$ACCT_NAME:localuser:" | awk -F: '{print $4}')
+	echo $LOCAL_ACCT_NAME $LOCAL_ACCT_PRIVILEGE $LOCAL_ACCT_CRYPT
+	PASS_CHECK -c $PWD_OLD:$LOCAL_ACCT_CRYPT
+	if [ $? -eq 1 ]; then
+		echo "Old password is not correct; try again."
+		break
+	fi
+	read -sp "Enter new password: " PWD_INPUT
+	echo ""
+	read -sp "Retype new password: " PWD_INPUT2
+	echo ""
+	NEWPASS_CHECK $PWD_INPUT $PWD_INPUT2
+	case $? in
+	0)
+		echo "God job!"
+		ACCT_PRIV=$(cat $PORTEX_TS_CONF | egrep "^$ACCT_NAME" | awk -F: '{print $3}')
+		PWD_SALT=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 8)
+		OUTPUT_CRYPT=$(mkpasswd --method=SHA-512 -S $PWD_SALT $PWD_INPUT)
+		echo $LOCAL_ACCT_NAME:localuser:$LOCAL_ACCT_PRIVILEGE:$OUTPUT_CRYPT
+		CONFIG_CHANGE -d $ACCT_NAME:localuser:
+		CONFIG_CHANGE -a $ACCT_NAME:localuser:$ACCT_PRIV:$OUTPUT_CRYPT
+		;;
+	1)
+		NEWPASS_NOTIFY
+		break
+		;;
+	2)
+		echo "User password does not match, try again."
+		;;
+	*)
+		echo "Fetal error."
+		break
+		;;
+	esac
 done
