Optimize script format

diff --git a/bin/cbox_ntpserver b/bin/cbox_ntpserver
--- a/bin/cbox_ntpserver
+++ b/bin/cbox_ntpserver
@@ -6,140 +6,140 @@ source /usr/local/bin/configmgmt
 
 PORTEX_TS_CONF="/home/portex/portex_ts.conf"
 
-
 prompt="Select function options: "
-options=("Show NTP server configuration" \
-	"Configure NTP server1" \
-	"Configure NTP server2" \
-	"Enable/Disable NTP function" \
-	"Test NTP server" \
-	)
+options=("Show NTP server configuration"
+	"Configure NTP server1"
+	"Configure NTP server2"
+	"Enable/Disable NTP function"
+	"Test NTP server"
+)
 
 echo ""
 PS3="$prompt "
-select opt in "${options[@]}" "Quit"; do 
-
-case "$REPLY" in
-
-1) echo "Show NTP server configuration: "
-	echo ""
-	declare -A PORTEX_CONF
-	CONFIG_READ $PORTEX_TS_CONF NTP_
-	echo -e "Current NTP function: ${PORTEX_CONF[NTP_ENABLE]}"
-	echo -e "Current NTP server1: ${PORTEX_CONF[NTP_SERVER1]}" 
-	echo -e "Current NTP server2: ${PORTEX_CONF[NTP_SERVER2]}"
-	echo ""
-	;;
-
-2) echo "Configure NTP server1: "
-	echo ""
-	declare -A PORTEX_CONF
-	CONFIG_READ $PORTEX_TS_CONF NTP_
-
-	echo -e "Current NTP server1: ${PORTEX_CONF[NTP_SERVER1]}"
-	echo ""
-	read -p "Are you sure to change the NTP information? (Y/N): " ANSWER
-	case $ANSWER in
-		Y) echo "Change NTP server1 configuration: "
+select opt in "${options[@]}" "Quit"; do
+	case "$REPLY" in
+	1)
+		echo "Show NTP server configuration: "
+		echo ""
+		declare -A PORTEX_CONF
+		CONFIG_READ $PORTEX_TS_CONF NTP_
+		echo -e "Current NTP function: ${PORTEX_CONF[NTP_ENABLE]}"
+		echo -e "Current NTP server1: ${PORTEX_CONF[NTP_SERVER1]}"
+		echo -e "Current NTP server2: ${PORTEX_CONF[NTP_SERVER2]}"
+		echo ""
+		;;
+	2)
+		echo "Configure NTP server1: "
+		echo ""
+		declare -A PORTEX_CONF
+		CONFIG_READ $PORTEX_TS_CONF NTP_
+		echo -e "Current NTP server1: ${PORTEX_CONF[NTP_SERVER1]}"
+		echo ""
+		read -p "Are you sure to change the NTP information? (Y/N): " ANSWER
+		case $ANSWER in
+		Y)
+			echo "Change NTP server1 configuration: "
 			echo ""
 			read -p "New NTP server1: " ANSWER_NTP
 			CONFIG_CHANGE -m "NTP_SERVER1=$ANSWER_NTP"
 			echo ""
 			;;
-		*) echo "NTP server1 configuration unchanged."
+		*)
+			echo "NTP server1 configuration unchanged."
 			echo ""
 			;;
-	esac
-	;;
-
-3) echo "Configure NTP server2: "
-        echo ""
-        declare -A PORTEX_CONF
-        CONFIG_READ $PORTEX_TS_CONF NTP_
-
-        echo -e "Current NTP server2: ${PORTEX_CONF[NTP_SERVER2]}"
-        echo ""
-        read -p "Are you sure to change the NTP information? (Y/N): " ANSWER
-        case $ANSWER in
-                Y) echo "Change NTP server2 configuration: "
-                        echo ""
-                        read -p "New NTP server2: " ANSWER_NTP
-                        CONFIG_CHANGE -m "NTP_SERVER2=$ANSWER_NTP"
-                        echo ""
-                        ;;
-                *) echo "NTP server2 configuration unchanged."
-                        echo ""
-                        ;;
-        esac
-        ;;
-
-4) echo "Enable or Disable NTP function: "
-	echo ""
-	declare -A PORTEX_CONF
-	CONFIG_READ $PORTEX_TS_CONF NTP_
-
-	echo -e "Current NTP function is ${PORTEX_CONF[NTP_ENABLE]}."
-	case ${PORTEX_CONF[NTP_ENABLE]} in
+		esac
+		;;
+	3)
+		echo "Configure NTP server2: "
+		echo ""
+		declare -A PORTEX_CONF
+		CONFIG_READ $PORTEX_TS_CONF NTP_
+		echo -e "Current NTP server2: ${PORTEX_CONF[NTP_SERVER2]}"
+		echo ""
+		read -p "Are you sure to change the NTP information? (Y/N): " ANSWER
+		case $ANSWER in
+		Y)
+			echo "Change NTP server2 configuration: "
+			echo ""
+			read -p "New NTP server2: " ANSWER_NTP
+			CONFIG_CHANGE -m "NTP_SERVER2=$ANSWER_NTP"
+			echo ""
+			;;
+		*)
+			echo "NTP server2 configuration unchanged."
+			echo ""
+			;;
+		esac
+		;;
+	4)
+		echo "Enable or Disable NTP function: "
+		echo ""
+		declare -A PORTEX_CONF
+		CONFIG_READ $PORTEX_TS_CONF NTP_
+		echo -e "Current NTP function is ${PORTEX_CONF[NTP_ENABLE]}."
+		case ${PORTEX_CONF[NTP_ENABLE]} in
 		ON)
 			echo ""
 			read -p "Do you want to switch NTP function to OFF? (Y/N): " ANSWER_ONOFF
 			case $ANSWER_ONOFF in
-				Y)
-					CONFIG_CHANGE -m "NTP_ENABLE=OFF"
-					echo "NTP function switch to OFF."
-					;;
-				*)
-					echo "NTP function no unchanged."
-					;;
+			Y)
+				CONFIG_CHANGE -m "NTP_ENABLE=OFF"
+				echo "NTP function switch to OFF."
+				;;
+			*)
+				echo "NTP function no unchanged."
+				;;
 			esac
 			;;
 		OFF)
 			echo ""
 			read -p "Do you want to switch NTP function to ON? (Y/N): " ANSWER_ON_OFF
 			case $ANSWER_ONOFF in
-				Y)
-					CONFIG_CHANGE -m "NTP_ENABLE=ON"
-					echo "NTP function switch to ON."
-					;;
-				*)
-					echo "NTP function unchanged/"
-					;;
+			Y)
+				CONFIG_CHANGE -m "NTP_ENABLE=ON"
+				echo "NTP function switch to ON."
+				;;
+			*)
+				echo "NTP function unchanged/"
+				;;
 			esac
 			;;
 		*)
 			echo "Fetal error."
 			exit 1
 			;;
-	esac
-	;;
-
-5) echo "Test NTP server."
-	echo ""
-	declare -A PORTEX_CONF
-	CONFIG_READ $PORTEX_TS_CONF NTP_
-	if [ -n $PORTEX_CONF[NTP_SERVER1]} ]; then
-		ping -c 1 ${PORTEX_CONF[NTP_SERVER1]} >/dev/null 2>&1
-		if [ $? -eq 0 ]; then
-			echo "Configured NTP server ${PORTEX_CONF[NTP_SERVER1]} is available."
-		else
-			echo "Configured NTP server ${PORTEX_CONF[NTP_SERVER1]} is unavailable."
+		esac
+		;;
+	5)
+		echo "Test NTP server."
+		echo ""
+		declare -A PORTEX_CONF
+		CONFIG_READ $PORTEX_TS_CONF NTP_
+		if [ -n $PORTEX_CONF[NTP_SERVER1]} ]; then
+			ping -c 1 ${PORTEX_CONF[NTP_SERVER1]} >/dev/null 2>&1
+			if [ $? -eq 0 ]; then
+				echo "Configured NTP server ${PORTEX_CONF[NTP_SERVER1]} is available."
+			else
+				echo "Configured NTP server ${PORTEX_CONF[NTP_SERVER1]} is unavailable."
+			fi
 		fi
-	fi
-	if [ -n $PORTEX_CONF[NTP_SERVER2]} ]; then
-                ping -c 1 ${PORTEX_CONF[NTP_SERVER2]} >/dev/null 2>&1
-                if [ $? -eq 0 ]; then
-                        echo "Configured NTP server ${PORTEX_CONF[NTP_SERVER2]} is available."
-                else
-                        echo "Configured NTP server ${PORTEX_CONF[NTP_SERVER2]} is unavailable."
-                fi
-        fi
-	;;
-
-$(( ${#options[@]}+1 )) ) echo "Goodbye!"; break;;
-
-*) echo "Invalid option. Try another one.";continue;;
-
-esac
-
+		if [ -n $PORTEX_CONF[NTP_SERVER2]} ]; then
+			ping -c 1 ${PORTEX_CONF[NTP_SERVER2]} >/dev/null 2>&1
+			if [ $? -eq 0 ]; then
+				echo "Configured NTP server ${PORTEX_CONF[NTP_SERVER2]} is available."
+			else
+				echo "Configured NTP server ${PORTEX_CONF[NTP_SERVER2]} is unavailable."
+			fi
+		fi
+		;;
+	$((${#options[@]} + 1)))
+		echo "Goodbye!"
+		break
+		;;
+	*)
+		echo "Invalid option. Try another one."
+		continue
+		;;
+	esac
 done
-
diff --git a/bin/configmgmt b/bin/configmgmt
--- a/bin/configmgmt
+++ b/bin/configmgmt
@@ -3,70 +3,72 @@
 # Routine for configuration manegement
 #
 
-function CONFIG_CHANGE(){
+function CONFIG_CHANGE() {
 	CONF_FILE="/home/portex/portex_ts.conf"
-
 	local OPTIND OPT m d a p
 	while getopts ":m:d:a:p:" OPT; do
 		case $OPT in
-			m)	# Usage: -m KEY_NAME=KEY_VALUE
-				#echo "Modify " $OPTARG
-				INPUT_KEY=`echo $OPTARG | awk -F= '{print $1}'`
-				INPUT_VAL=$OPTARG
-				#echo $INPUT_KEY $INPUT_VAL
-				#cat $CONF_FILE | egrep -v '#' | egrep $INPUT_KEY >/dev/null 2>&1
-				sed -i "s/^$INPUT_KEY=.*$/$INPUT_VAL/" $CONF_FILE
+		m) # Usage: -m KEY_NAME=KEY_VALUE
+			#echo "Modify " $OPTARG
+			INPUT_KEY=$(echo $OPTARG | awk -F= '{print $1}')
+			INPUT_VAL=$OPTARG
+			#echo $INPUT_KEY $INPUT_VAL
+			#cat $CONF_FILE | egrep -v '#' | egrep $INPUT_KEY >/dev/null 2>&1
+			sed -i "s/^$INPUT_KEY=.*$/$INPUT_VAL/" $CONF_FILE
+			;;
+		d) # Usage: -d ACL_IN=A.B.C.D/E or -d LOCAL_ACCT:localuser:
+			#				echo "Delete " $OPTARG
+			INPUT_VAL=$OPTARG
+			echo $INPUT_VAL | egrep 'ACL_IN' >/dev/null 2>&1
+			[ $? -eq 0 ] && ARG_TYPE=ACL
+			echo $INPUT_VAL | egrep ':localuser:' >/dev/null 2>&1
+			[ $? -eq 0 ] && ARG_TYPE=ACCT
+			case $ARG_TYPE in
+			ACL)
+				echo "$INPUT_VAL is ACL type."
+				sed -i "\|^$INPUT_VAL|d" $CONF_FILE
 				;;
-			d)	# Usage: -d ACL_IN=A.B.C.D/E or -d LOCAL_ACCT:localuser:
-#				echo "Delete " $OPTARG
-				INPUT_VAL=$OPTARG
-				echo $INPUT_VAL | egrep 'ACL_IN' >/dev/null 2>&1; [ $? -eq 0 ] && ARG_TYPE=ACL
-				echo $INPUT_VAL | egrep ':localuser:' >/dev/null 2>&1; [ $? -eq 0 ] && ARG_TYPE=ACCT
-				case $ARG_TYPE in
-					ACL)
-						echo "$INPUT_VAL is ACL type."
-						sed -i "\|^$INPUT_VAL|d" $CONF_FILE
-						;;
-					ACCT)
-						echo "$INPUT_VAL is ACCT type"
-						sed -i "\|^$INPUT_VAL|d" $CONF_FILE
-						;;
-				esac
+			ACCT)
+				echo "$INPUT_VAL is ACCT type"
+				sed -i "\|^$INPUT_VAL|d" $CONF_FILE
 				;;
-			a)	# Usage: -a ACL_IN=A.B.C.D/E or -a ACCOUNT_NAME:localuser:ACCOUNT_PRIVILEGE:ACCOUNT_PASSWORD
-#				echo "Add " $OPTARG
-				INPUT_VAL=$OPTARG
-				echo $INPUT_VAL | egrep 'ACL_IN' >/dev/null 2>&1; [ $? -eq 0 ] && ARG_TYPE=ACL
-				echo $INPUT_VAL | egrep ':localuser:' >/dev/null 2>&1; [ $? -eq 0 ] && ARG_TYPE=ACCT
-				case $ARG_TYPE in
-					ACL)
-						echo "$INPUT_VAL is ACL type."
-						cat $CONF_FILE | egrep $INPUT_VAL >/dev/null 2>&1
-						[ $? -eq 0 ] || sed -i "/# ACL entries begin/ a $INPUT_VAL" $CONF_FILE
-						;;
-					ACCT)
-						echo "$INPUT_VAL is ACCT type."
-						sed -i "/# Local account entries begin/ a $INPUT_VAL" $CONF_FILE
-						;;
-				esac
+			esac
+			;;
+		a) # Usage: -a ACL_IN=A.B.C.D/E or -a ACCOUNT_NAME:localuser:ACCOUNT_PRIVILEGE:ACCOUNT_PASSWORD
+			#				echo "Add " $OPTARG
+			INPUT_VAL=$OPTARG
+			echo $INPUT_VAL | egrep 'ACL_IN' >/dev/null 2>&1
+			[ $? -eq 0 ] && ARG_TYPE=ACL
+			echo $INPUT_VAL | egrep ':localuser:' >/dev/null 2>&1
+			[ $? -eq 0 ] && ARG_TYPE=ACCT
+			case $ARG_TYPE in
+			ACL)
+				echo "$INPUT_VAL is ACL type."
+				cat $CONF_FILE | egrep $INPUT_VAL >/dev/null 2>&1
+				[ $? -eq 0 ] || sed -i "/# ACL entries begin/ a $INPUT_VAL" $CONF_FILE
 				;;
-			p)	# Usage -p ACCOUNT_NAME:localuser:ACCOUNT_PRIVILEGE:ACCOUNT_PASSWORD
-#				echo "Change password"
-				INPUT_VAL=$OPTARG
-				ACCT_NAME=`echo $INPUT_VAL | awk -F: '{print $1}'`
-				sed -i "\|^$ACCT_NAME|d" $CONF_FILE
+			ACCT)
+				echo "$INPUT_VAL is ACCT type."
 				sed -i "/# Local account entries begin/ a $INPUT_VAL" $CONF_FILE
 				;;
-			:)
-				echo "Invalid argument."
-				;;
-			*)
-				echo "Invalid option."
-				;;
+			esac
+			;;
+		p) # Usage -p ACCOUNT_NAME:localuser:ACCOUNT_PRIVILEGE:ACCOUNT_PASSWORD
+			#				echo "Change password"
+			INPUT_VAL=$OPTARG
+			ACCT_NAME=$(echo $INPUT_VAL | awk -F: '{print $1}')
+			sed -i "\|^$ACCT_NAME|d" $CONF_FILE
+			sed -i "/# Local account entries begin/ a $INPUT_VAL" $CONF_FILE
+			;;
+		:)
+			echo "Invalid argument."
+			;;
+		*)
+			echo "Invalid option."
+			;;
 		esac
 	done
 }
-
 
 #function importconf(){
 #        CONF_FILE=$1
@@ -86,20 +88,20 @@ function CONFIG_CHANGE(){
 #        fi
 #}
 
-function CONFIG_READ(){
-        CONF_FILE=$1
-        CONF_KEY=$2
-        if [ -n $CONF_KEY ]; then
-                for ITEM in `cat $CONF_FILE | egrep -v '#' | egrep $CONF_KEY`; do
-                        KEY=`echo $ITEM | awk -F= '{print $1}'`
-                        VALUE=`echo $ITEM | awk -F= '{print $2}'`
-                        PORTEX_CONF[$KEY]=$VALUE
-                done
-        else
-                for ITEM in `cat $CONF_FILE | egrep -v '#'`; do
-                        KEY=`echo $ITEM | awk -F= '{print $1}'`
-                        VALUE=`echo $ITEM | awk -F= '{print $2}'`
-                        PORTEX_CONF[$KEY]=$VALUE
-                done
-        fi
+function CONFIG_READ() {
+	CONF_FILE=$1
+	CONF_KEY=$2
+	if [ -n $CONF_KEY ]; then
+		for ITEM in $(cat $CONF_FILE | egrep -v '#' | egrep $CONF_KEY); do
+			KEY=$(echo $ITEM | awk -F= '{print $1}')
+			VALUE=$(echo $ITEM | awk -F= '{print $2}')
+			PORTEX_CONF[$KEY]=$VALUE
+		done
+	else
+		for ITEM in $(cat $CONF_FILE | egrep -v '#'); do
+			KEY=$(echo $ITEM | awk -F= '{print $1}')
+			VALUE=$(echo $ITEM | awk -F= '{print $2}')
+			PORTEX_CONF[$KEY]=$VALUE
+		done
+	fi
 }
diff --git a/bin/passwdmgmt b/bin/passwdmgmt
--- a/bin/passwdmgmt
+++ b/bin/passwdmgmt
@@ -9,95 +9,87 @@
 #
 #
 # New password policy statement
-function NEWPASS_NOTIFY(){
-        echo "Password Strength Requirement:"
-        echo "  1: At least 8 characters long."
-        echo "  2: Include three of the following four factors:"
-        echo "          A. Numbers."
-        echo "          B. Letters in uppercase."
-        echo "          C. Letters in lowercase."
-        echo "          D. Symbols."
-        echo ""
+function NEWPASS_NOTIFY() {
+	echo "Password Strength Requirement:"
+	echo "  1: At least 8 characters long."
+	echo "  2: Include three of the following four factors:"
+	echo "          A. Numbers."
+	echo "          B. Letters in uppercase."
+	echo "          C. Letters in lowercase."
+	echo "          D. Symbols."
+	echo ""
 }
 
 # New password check routine
 #
 # Usage: NEWPASS_CHECK NEW_PASSWD_1 NEW_PASSWD_2
-function NEWPASS_CHECK(){
+function NEWPASS_CHECK() {
 	INPUT_PASS1="$1"
 	INPUT_PASS2="$2"
-	
-if [ $INPUT_PASS1 == $INPUT_PASS2 ]; then
 
-	declare -i LEN_SCORE=0
-	declare -a PWD_SCORE=(0 0 0 0)
-
-	CHAR_COUNT=`echo ${#INPUT_PASS1}`; [ $CHAR_COUNT -ge 8 ] && LEN_SCORE=1
-	echo $INPUT_PASS1 | egrep "[A-Z]" >/dev/null 2>&1; [ $? -eq 0 ] && PWD_SCORE[0]=1
-	echo $INPUT_PASS1 | egrep "[a-z]" >/dev/null 2>&1; [ $? -eq 0 ] && PWD_SCORE[1]=1
-	echo $INPUT_PASS1 | egrep "[0-9]" >/dev/null 2>&1; [ $? -eq 0 ] && PWD_SCORE[2]=1
-	echo $INPUT_PASS1 | egrep "[!@#$%^&*()]" >/dev/null 2>&1; [ $? -eq 0 ] && PWD_SCORE[3]=1
-
-	declare -i SUM_SCORE=0
-	for i in ${PWD_SCORE[@]}; do
-		SUM_SCORE+=$i
-	done
-
-	declare -i SCORE_RESULT=0
-	SCORE_RESULT=$(($LEN_SCORE * $SUM_SCORE))
-
-	if [ $SCORE_RESULT -ge 3 ]; then
-		return 0
+	if [ $INPUT_PASS1 == $INPUT_PASS2 ]; then
+		declare -i LEN_SCORE=0
+		declare -a PWD_SCORE=(0 0 0 0)
+		CHAR_COUNT=$(echo ${#INPUT_PASS1})
+		[ $CHAR_COUNT -ge 8 ] && LEN_SCORE=1
+		echo $INPUT_PASS1 | egrep "[A-Z]" >/dev/null 2>&1
+		[ $? -eq 0 ] && PWD_SCORE[0]=1
+		echo $INPUT_PASS1 | egrep "[a-z]" >/dev/null 2>&1
+		[ $? -eq 0 ] && PWD_SCORE[1]=1
+		echo $INPUT_PASS1 | egrep "[0-9]" >/dev/null 2>&1
+		[ $? -eq 0 ] && PWD_SCORE[2]=1
+		echo $INPUT_PASS1 | egrep "[!@#$%^&*()]" >/dev/null 2>&1
+		[ $? -eq 0 ] && PWD_SCORE[3]=1
+		declare -i SUM_SCORE=0
+		for i in ${PWD_SCORE[@]}; do
+			SUM_SCORE+=$i
+		done
+		declare -i SCORE_RESULT=0
+		SCORE_RESULT=$(($LEN_SCORE * $SUM_SCORE))
+		if [ $SCORE_RESULT -ge 3 ]; then
+			return 0
+		else
+			return 1
+		fi
 	else
-		return 1
+		return 2
 	fi
-
-else
-	return 2
-fi
-
 }
-
 
 #
 # Old password check routine
 #
 # Usage: OLDPASS_CHECK PASSWD_TO_CHECK ENCRYPT_PASSWD
-function OLDPASS_CHECK(){
+function OLDPASS_CHECK() {
 	INPUT_PASSWD="$1"
 	INPUT_CRYPT="$2"
-
-	INPUT_SALT=`echo $INPUT_CRYPT | awk -F$ '{print $3}'`
-	OUTPUT_CRYPT=`/usr/bin/mkpasswd --method=SHA-512 -S $INPUT_SALT $INPUT_PASSWD`
-
+	INPUT_SALT=$(echo $INPUT_CRYPT | awk -F$ '{print $3}')
+	OUTPUT_CRYPT=$(/usr/bin/mkpasswd --method=SHA-512 -S $INPUT_SALT $INPUT_PASSWD)
 	if [ $INPUT_CRYPT == $OUTPUT_CRYPT ]; then
 		return 0
 	else
 		return 1
 	fi
-
 }
 
-
-function PASS_CHECK(){
+function PASS_CHECK() {
 	local OPTIND OPT c n
-        while getopts ":c:n:" OPT; do
-            set -f
-            IFS=':'
-            declare PWD_ARRAY=($2)
-            case $OPT in
-                c)
-					OLDPASS_CHECK ${PWD_ARRAY[0]} ${PWD_ARRAY[1]}
-					return $?
-                    ;;
-                n)
-					NEWPASS_CHECK ${PWD_ARRAY[0]} ${PWD_ARRAY[1]}
-					return $?
-                    ;;
-                *)
-                    echo "Invalid option/argument."
-                    ;;
-            esac
-        done
+	while getopts ":c:n:" OPT; do
+		set -f
+		IFS=':'
+		declare PWD_ARRAY=($2)
+		case $OPT in
+		c)
+			OLDPASS_CHECK ${PWD_ARRAY[0]} ${PWD_ARRAY[1]}
+			return $?
+			;;
+		n)
+			NEWPASS_CHECK ${PWD_ARRAY[0]} ${PWD_ARRAY[1]}
+			return $?
+			;;
+		*)
+			echo "Invalid option/argument."
+			;;
+		esac
+	done
 }
-
diff --git a/bin/regreport b/bin/regreport
--- a/bin/regreport
+++ b/bin/regreport
@@ -1,5 +1,6 @@
 #!/bin/bash
-
+#
+#
 source /usr/local/bin/writelog
 source /usr/local/bin/configmgmt
 PORTEX_TS_CONF="/home/portex/portex_ts.conf"
@@ -21,7 +22,7 @@ else
 fi
 
 /bin/nc -vz -w 3 ${PORTEX_CONF[TAC_SERVER2_IP]} 49 &>/dev/null 2>&1
-if [ $? -eq 0 ] ; then
+if [ $? -eq 0 ]; then
 	TAC_SERVER2_STATUS="OK"
 	[ $VERBOSE_FLAG == "ON" ] && echo "Connect TACACS+ Server2(${PORTEX_CONF[TAC_SERVER2_IP]}) is available."
 else
@@ -31,10 +32,10 @@ fi
 
 /usr/sbin/ntpdate ${PORTEX_CONF[NTP_SERVER1]} &>/dev/null 2>&1
 if [ $? -eq 0 ]; then
-        NTP_STATUS="ntp sync"
+	NTP_STATUS="ntp sync"
 else
-        echo NTP_SERVER1_STATUS="FAILED"
-        /usr/sbin/ntpdate ${PORTEX_CONF[NTP_SERVER2]} &>/dev/null 2>&1
+	echo NTP_SERVER1_STATUS="FAILED"
+	/usr/sbin/ntpdate ${PORTEX_CONF[NTP_SERVER2]} &>/dev/null 2>&1
 	if [ $? -eq 0 ]; then
 		NTP_STATUS="ntp sync"
 	else
@@ -42,10 +43,9 @@ else
 	fi
 fi
 
-SYSTEM_BOOTTIME=`uptime -s`
-SYSTEM_UPTIME=`uptime -p`
+SYSTEM_BOOTTIME=$(uptime -s)
+SYSTEM_UPTIME=$(uptime -p)
 
 [ ${PORTEX_CONF[LOG_ENABLE]} == "ON" ] && write_log_buffer auth info TACACS \
 	"TAC_SERVER1(${PORTEX_CONF[TAC_SERVER1_IP]})=$TAC_SERVER1_STATUS, TAC_SERVER2(${PORTEX_CONF[TAC_SERVER2_IP]}); \
 	System $SYSTEM_UPTIME since $SYSTEM_BOOTTIME ($NTP_STATUS)"
-
diff --git a/bin/tscheck b/bin/tscheck
--- a/bin/tscheck
+++ b/bin/tscheck
@@ -10,18 +10,18 @@ trap "CONFIG_READ $PORTEX_TS_CONF RCHK_" SIGHUP
 
 CONFIG_READ $PORTEX_TS_CONF RCHK_
 
-if [ -z "$1" ];then
-        declare PERIOD=${PORTEX_CONF[RCHK_TACSVR]}
+if [ -z "$1" ]; then
+	declare PERIOD=${PORTEX_CONF[RCHK_TACSVR]}
 else
-		declare PERIOD=${PORTEX_CONF[RCHK_TACSVR]}
-		[ `echo $1 | egrep '^[0-9]+$'` ] && PERIOD=$1	# Check if $1 is an interger
+	declare PERIOD=${PORTEX_CONF[RCHK_TACSVR]}
+	[ $(echo $1 | egrep '^[0-9]+$') ] && PERIOD=$1 # Check if $1 is an interger
 fi
 
 TAC_SERVER_INFO="/home/portex/portex_ts.conf"
 
-function TAC_TEST(){
-	TAC_SERVER1=`cat $TAC_SERVER_INFO | egrep -v '#' | egrep TAC_SERVER1_IP | awk -F= '{print $2}'`
-	TAC_SERVER2=`cat $TAC_SERVER_INFO | egrep -v '#' | egrep TAC_SERVER2_IP | awk -F= '{print $2}'`
+function TAC_TEST() {
+	TAC_SERVER1=$(cat $TAC_SERVER_INFO | egrep -v '#' | egrep TAC_SERVER1_IP | awk -F= '{print $2}')
+	TAC_SERVER2=$(cat $TAC_SERVER_INFO | egrep -v '#' | egrep TAC_SERVER2_IP | awk -F= '{print $2}')
 
 	/bin/nc -vz -w 3 $TAC_SERVER1 49 &>/dev/null 2>&1
 	if [ $? -eq 0 ]; then
@@ -29,22 +29,20 @@ function TAC_TEST(){
 		echo "BLUE LED ON"
 		echo -e "blue_on\c" | nc -q 1 -U /var/run/uds_led
 		TSC_FLAG=1
-
 	else
-	        echo "Connect TACACS+ server1 unsuccessfully"
-	        /bin/nc -vz -w 3 $TAC_SERVER2 49 &>/dev/null 2>&1
-	        if [ $? -eq 0 ]; then
-	                echo "Connect TACACS+ server2 successfully"
-			echo "BLUE LED ON"
-			echo -e "blue_on\c" | nc -q 1 -U /var/run/uds_led
-	                TSC_FLAG=1
-	        else
-	                echo "Connect TACACS+ Server2 unsuccessfully"
-			echo "BLUE LED OFF"
-			echo -e "blue_off\c" | nc -q 1 -U /var/run/uds_led
+		echo "Connect TACACS+ server1 unsuccessfully"
+		/bin/nc -vz -w 3 $TAC_SERVER2 49 &>/dev/null 2>&1
+		if [ $? -eq 0 ]; then
+			echo "Connect TACACS+ server2 successfully"
+			cho "BLUE LED ON"
+			cho -e "blue_on\c" | nc -q 1 -U /var/run/uds_led
+			TSC_FLAG=1
+		else
+			echo "Connect TACACS+ Server2 unsuccessfully"
+			cho "BLUE LED OFF"
+			cho -e "blue_off\c" | nc -q 1 -U /var/run/uds_led
 			TSC_FLAG=0
-
-	        fi
+		fi
 	fi
 	echo ""
 }
@@ -67,52 +65,51 @@ declare TAC_FAIL=0
 while [ TRUE ]; do
 	echo "Last status is $LAST_STATUS"
 	case $LAST_STATUS in
-		OKOK)
-			echo "New status is OKOK"
-			COUNT=1
-			while [ $COUNT -le 4 ]; do
-				sleep $PERIOD
-				TAC_TEST
-				if [ $TSC_FLAG -eq 1 ];then
-					TAC_OKOK=0
+	OKOK)
+		echo "New status is OKOK"
+		COUNT=1
+		while [ $COUNT -le 4 ]; do
+			sleep $PERIOD
+			TAC_TEST
+			if [ $TSC_FLAG -eq 1 ]; then
+				TAC_OKOK=0
+				TAC_FAIL=0
+				break
+			else
+				TAC_FAIL=$((TAC_FAIL + 1))
+				COUNT=$((COUNT + 1))
+				echo "TAC_FAIL count is $TAC_FAIL"
+				if [ $TAC_FAIL -eq 4 ]; then
+					echo "Send loss log"
+					write_log_buffer cron crit TACACS "Loss ALL TACACS+ server connection!"
 					TAC_FAIL=0
-					break
-				else
-					TAC_FAIL=$((TAC_FAIL + 1))
-					COUNT=$((COUNT + 1))
-					echo "TAC_FAIL count is $TAC_FAIL"
-					if [ $TAC_FAIL -eq 4 ];then
-						echo "Send loss log"
-						write_log_buffer cron crit TACACS "Loss ALL TACACS+ server connection!"
-						TAC_FAIL=0
-						LAST_STATUS="FAIL"
-					fi
+					LAST_STATUS="FAIL"
 				fi
-			done
-			;;
-		FAIL)
-			echo "New status is FAILED"
-			COUNT=1
-			while [ $COUNT -le 4 ]; do
-				sleep $PERIOD
-				TAC_TEST
-				if [ $TSC_FLAG -eq 0 ];then
-					TAC_FAIL=0
+			fi
+		done
+		;;
+	FAIL)
+		echo "New status is FAILED"
+		COUNT=1
+		while [ $COUNT -le 4 ]; do
+			sleep $PERIOD
+			TAC_TEST
+			if [ $TSC_FLAG -eq 0 ]; then
+				TAC_FAIL=0
+				TAC_OKOK=0
+				break
+			else
+				TAC_OKOK=$((TAC_OKOK + 1))
+				COUNT=$((COUNT + 1))
+				echo "TAC_OKOK count is $TAC_OKOK"
+				if [ $TAC_OKOK -eq 4 ]; then
+					echo "Send restore log"
+					write_log_buffer cron notice TACACS "One of TACACS+ server connection restore."
 					TAC_OKOK=0
-					break
-				else
-					TAC_OKOK=$((TAC_OKOK + 1))
-					COUNT=$((COUNT + 1))
-					echo "TAC_OKOK count is $TAC_OKOK"
-					if [ $TAC_OKOK -eq 4 ];then
-						echo "Send restore log"
-						write_log_buffer cron notice TACACS  "One of TACACS+ server connection restore."
-						TAC_OKOK=0
-						LAST_STATUS="OKOK"
-					fi
+					LAST_STATUS="OKOK"
 				fi
-			done
-			;;
+			fi
+		done
+		;;
 	esac
 done
-
