Add NTP regular sync

diff --git a/bin/regreport b/bin/regreport
--- a/bin/regreport
+++ b/bin/regreport
@@ -8,6 +8,7 @@ VERBOSE_FLAG=OFF
 declare -A PORTEX_CONF
 CONFIG_READ $PORTEX_SYS TAC_
 CONFIG_READ $PORTEX_SYS LOG_
+CONFIG_READ $PORTEX_SYS NTP_
 echo ${PORTEX_CONF[LOG_ENABLE]}
 
 /bin/nc -vz -w 3 ${PORTEX_CONF[TAC_SERVER1_IP]} 49 &>/dev/null 2>&1
@@ -28,10 +29,23 @@ else
 	[ $VERBOSE_FLAG == "ON" ] && echo "Connect TACACS+ Server2(${PORTEX_CONF[TAC_SERVER2_IP]}) is unavailable."
 fi
 
+/usr/sbin/ntpdate ${PORTEX_CONF[NTP_SERVER1]} &>/dev/null 2>&1
+if [ $? -eq 0 ]; then
+        NTP_STATUS="ntp sync"
+else
+        echo NTP_SERVER1_STATUS="FAILED"
+        /usr/sbin/ntpdate ${PORTEX_CONF[NTP_SERVER2]} &>/dev/null 2>&1
+	if [ $? -eq 0 ]; then
+		NTP_STATUS="ntp sync"
+	else
+		NTP_STATUS="ntp unsync"
+	fi
+fi
+
 SYSTEM_BOOTTIME=`uptime -s`
 SYSTEM_UPTIME=`uptime -p`
 
 [ ${PORTEX_CONF[LOG_ENABLE]} == "ON" ] && write_log_buffer auth info TACACS \
 	"TAC_SERVER1(${PORTEX_CONF[TAC_SERVER1_IP]})=$TAC_SERVER1_STATUS, TAC_SERVER2(${PORTEX_CONF[TAC_SERVER2_IP]}); \
-	System $SYSTEM_UPTIME since $SYSTEM_BOOTTIME"
+	System $SYSTEM_UPTIME since $SYSTEM_BOOTTIME ($NTP_STATUS)"
 
